"""
Generate Engine - controlled missingness injector (Section 3 of the spec doc).

Reads config/null_injection_rates.yaml and nulls fields on synthetic transactions
at realistic rates, INCLUDING MNAR-style nulls tied to specific fraud scenarios
(e.g. anti-fingerprinting tooling -> null device_fingerprint).

Every nulled field gets a companion "<field>_was_null" flag so downstream models
can use missingness itself as a signal, per the spec.
"""

import random
from typing import Optional

import yaml


class NullInjector:
    def __init__(self, config_path: str = "config/null_injection_rates.yaml", seed: int = 42):
        with open(config_path) as f:
            self.config = yaml.safe_load(f)["fields"]
        random.seed(seed)

    def apply(self, txn: dict, scenario: Optional[dict] = None) -> dict:
        """Mutates a copy of txn in place, applying null-injection rules. Returns the copy."""
        txn = dict(txn)  # shallow copy is fine, we only touch top-level + deviceDetails
        txn["deviceDetails"] = dict(txn.get("deviceDetails") or {})

        # --- device_fingerprint (nested under deviceDetails.deviceId, treated as the
        # canonical "device_fingerprint" field per the spec's Identity/Device table) ---
        rule = self.config["device_fingerprint"]
        rate = rule["rate"] if txn.get("channel") == "CNP" else rule["fallback_rate"]

        # MNAR override: if this transaction was generated by an anti-fingerprinting
        # scenario, force near-certain nullification regardless of channel.
        mnar_rule = self.config.get("device_fingerprint_anti_fingerprinting")
        if scenario and mnar_rule:
            is_anti_fp_scenario = (
                scenario.get("manipulation_type") == "network"
                and "Anti-Fingerprinting" in scenario.get("f3_technique", "")
            )
            if is_anti_fp_scenario:
                rate = mnar_rule["rate"]

        if random.random() < rate:
            txn["deviceDetails"]["deviceId"] = None
            txn["device_fingerprint_was_null"] = True
        else:
            txn["device_fingerprint_was_null"] = False

        # --- ip_asn_risk_score (MCAR, always applies) ---
        rule = self.config["ip_asn_risk_score"]
        if random.random() < rule["rate"]:
            txn["ip_asn_risk_score"] = None
            txn["ip_asn_risk_score_was_null"] = True
        else:
            # placeholder score - real value would come from an ASN lookup in the feature pipeline
            txn["ip_asn_risk_score"] = round(random.random(), 3)
            txn["ip_asn_risk_score_was_null"] = False

        # --- mcc -> explicit "unknown" category, NOT a null (mode-imputation avoidance) ---
        rule = self.config["mcc"]
        if random.random() < rule["rate"]:
            txn["mcc"] = "unknown"

        # --- cold-start behavioral default for new accounts ---
        account_age_days = txn.get("account_age_days", 999)
        if account_age_days < 7:
            txn["login_time_deviation_hrs"] = 0.0  # population baseline placeholder
            txn["is_new_account"] = True
        else:
            txn["is_new_account"] = False

        # --- graph centrality structural zero for brand-new accounts (not null) ---
        if account_age_days < 1:
            txn["graph_centrality"] = 0

        return txn

    def apply_batch(self, txns: list[dict], scenario: Optional[dict] = None) -> list[dict]:
        return [self.apply(t, scenario) for t in txns]


if __name__ == "__main__":
    from legit_traffic_sim import LegitTrafficSimulator

    sim = LegitTrafficSimulator()
    injector = NullInjector()

    batch = sim.generate_batch(n_accounts=3, txns_per_account_range=(2, 2))
    injected = injector.apply_batch(batch)

    null_count = sum(1 for t in injected if t["deviceDetails"]["deviceId"] is None)
    print(f"{null_count}/{len(injected)} transactions had device_fingerprint nulled")
    import json
    print(json.dumps(injected[0], indent=2, default=str))
